version: '3.7'

services:
  rmq:
    image: rabbitmq:3.8.3-alpine

  orchestrator:
    container_name: orch
    build:
        context: ./orchestrator
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
        - .:/code
    depends_on:
        - rmq
    restart: on-failure    

  