version: '3.7'

services:
  orchestrator:
    container_name: orch
    build:
        context: ./orchestrator
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
        - ./orchestrator:/app
    depends_on:
        - rmq
    restart: on-failure
  rmq:
    image: rabbitmq:3.8.3-alpine    

  
  slave:
      build:
          context: ./slave
          dockerfile: Dockerfile
      command: sh -c "sleep 5 && python slave.py"
      volumes:
      - ./slave:/code
      restart: on-failure
    rmq:
      image: rabbitmq:3.8.3-alpine  

  master:
      build:
          context: ./master
          dockerfile: Dockerfile
      command: sh -c "sleep 5 && python master.py"
      volumes:
      - ./master:/code
      restart: on-failure
    rmq:
      image: rabbitmq:3.8.3-alpine  