version: '3.7'

networks:
  dbaas-network:
   name: dbaas-network

services:
  rmq:
    container_name: rmq_host
    image: rabbitmq:3.8.3-alpine
    networks:
      - dbaas-network
  
  zoo:
    container_name: zoo
    image: zookeeper
    networks:
      - dbaas-network

  orchestrator:
    container_name: orch
    build:
        context: ./orchestrator
        dockerfile: Dockerfile
    command: sh -c "sleep 15 && chmod a+x run.sh && ./run.sh"
    ports:
      - "5000:5000"
    volumes:
        - ./orchestrator:/app
        - ./master_slave:/master_slave
        - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
    depends_on:
        - rmq
        - orch_mongo
    networks:
      - dbaas-network
    restart: on-failure
  
  orch_mongo:
    container_name: orch_mongo
    image: mongo
    networks:
      - dbaas-network
    restart: always

  slave:
    container_name: slave
    build:
          context: ./master_slave
          dockerfile: Dockerfile
    command: sh -c "sleep 15 && python -u master_slave.py slave"
    volumes:
        - ./master_slave:/master_slave
    depends_on:
        - rmq
        - s_mongo
    networks:
      - dbaas-network
    restart: on-failure

  s_mongo:
    container_name: s_mongo
    image: mongo
    networks:
      - dbaas-network
    restart: always


  master:
    container_name: master
    build:
          context: ./master_slave
          dockerfile: Dockerfile
    command: sh -c "sleep 15 && python -u master_slave.py master"
    volumes:
          - ./master_slave:/master_slave
    depends_on:
        - rmq
        - m_mongo
    networks:
      - dbaas-network
    restart: on-failure

  m_mongo:
    container_name: m_mongo
    image: mongo
    volumes:
      - ./orchestrator:/data
    networks:
      - dbaas-network
    restart: always
  
