version: '3.7'

services:
  rmq:
    image: rabbitmq:3.8.3-alpine
  orchestrator:
    container_name: orch
    build:
        context: ./orchestrator
        dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
        - ./orchestrator:/app
    links:
    - rmq
    depends_on:
        - rmq
    restart: on-failure

  slave:
    container_name: slave
    build:
          context: ./slave
          dockerfile: Dockerfile
    command: sh -c "sleep 5 && python slave.py"
    volumes:
        - ./slave:/slave
    links:
    - rmq
    - slave_mongo
    depends_on:
        - rmq
        - slave_mongo
    restart: on-failure

  slave_mongo:
    image: mongo
    restart: always


  master:
    container_name: master
    build:
          context: ./master
          dockerfile: Dockerfile
    command: sh -c "sleep 5 && python master.py"
    volumes:
          - ./master:/master
    links:
    - rmq
    - master_mongo
    depends_on:
        - rmq
        - master_mongo
    restart: on-failure

  master_mongo:
    image: mongo
    restart: always
  
  
