version: '3.7'

networks:
  dbaas-network: #Internal network to avoid issues with naming conventions.
   name: dbaas-network 

services: # Services are discoverable by their names. They connect to the dbaas-network
  rmq:
    container_name: rmq_host
    image: rabbitmq:3.8.3-alpine
    networks:
      - dbaas-network
  
  zoo:
    container_name: zoo
    image: zookeeper
    networks:
      - dbaas-network

  orchestrator:
    container_name: orch
    build:
        context: ./orchestrator
        dockerfile: Dockerfile
    command: sh -c "sleep 15 && chmod a+x run.sh && ./run.sh" #Sleep is for zoo and rmq to init
    environment:
      - HOSTPWD=$PWD
    ports:
      - "80:80"
    volumes:
        - ./orchestrator:/app
        - ./master_slave:/master_slave
        - "/var/run/docker.sock:/var/run/docker.sock" #Access host docker engine
    privileged: true
    depends_on:
        - rmq
        - orch_mongo
    networks:
      - dbaas-network
    restart: on-failure
  
  orch_mongo:
    container_name: orch_mongo
    image: mongo
    networks:
      - dbaas-network
    restart: always
  
